[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bottle = "G36SiH1Cp3kyFazCwTd18t753JHchYKyxEriwQvZMead"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build-client = "cargo build --manifest-path cmd/Cargo.toml"
